---
title: "Coursework B"
author: "..."
output: html_notebook
---



```{r}
d <- read.csv("data.csv")
str(d)
```

```{r}
table(d$model, d$TeD)
```

```{r}
d$modeltype = factor(substring(d$model, 1, 1))
d$modelnr = factor(substring(d$model, 2))
temp = subset(d, select=c("TrD1", "TrD2", "TrD3", "TrD4", "TrD5", "TrD6", "TrD7", "TrD8"))
d$trdcount = factor(rowSums(temp, dims=1))
d$model = factor(d$model)
```

```{r}
d
```

```{r fig.width=7, fig.height=3}
library(ggplot2)

ggplot(d[d$modeltype == "B",], aes(x=score, y=modelnr)) + geom_point(aes(col=TeD), alpha=0.5, size=5) + ggtitle("Baseline models")
```

```{r fig.width=7, fig.height=2}
ggplot(d[d$modeltype == "S",], aes(x=score, fill=TeD)) + geom_histogram() + ggtitle("Single TrD model")
```

```{r fig.width=7, fig.height=10}
ggplot(d[d$modeltype == "M",], aes(x=score, fill=TeD)) + geom_histogram() + facet_grid(modelnr ~ .) + ggtitle("Multiple TrD models")
```

```{r fig.width=7, fig.height=4}
ggplot(d, aes(x=trdcount, y=score)) + geom_boxplot(outlier.shape = NA) + geom_jitter(width = 0.2, alpha=0.3, size=1, aes(col=modeltype))
```

# Conceptual model

## Research question 1

*How much does transfer learning improve over typical non-transfer learning?*

## Researh question 2

*What is the effect of the TrD’s on the final model performance?*

# Tests to perform

```{r}

```
